# form UDON/UdonBehaviour.cs
event_table = {
  '_start': (),
  '_update': (),
  '_lateUpdate': (), 
  '_interact': (),
  '_fixedUpdate': (),
  '_onAnimatorIk': (('SystemInt32', 'onAnimatorIkLayerIndex'),), # ok
  '_onAnimatorMove': (),
  '_onAudioFilterRead': (('SystemSingleArray','onAudioFilterReadData', 'onAudioFilterReadChannels', 'SystemInt32')), # ok
  '_onBecameInvisible': (),
  '_onBecameVisible': (),
  '_onCollisionEnter': (('UnityEngineCollision', 'onCollisionEnterOther'),),
  '_onCollisionEnter2D': (('UnityEngineCollision2D', 'onCollisionEnter2DOther'),),
  '_onCollisionExit': (('UnityEngineCollision', 'onCollisionExitOther'),),
  '_onCollisionExit2D': (('UnityEngineCollision2D', 'onCollisionExit2DOther'),),
  '_onCollisionStay': (('UnityEngineCollision', 'onCollisionStayOther'),),
  '_onCollisionStay2D': (('UnityEngineCollision2D', 'onCollisionStay2DOther'),),
  # '_onControllerColliderHit': ('UnityEngineControllerColliderHit', 'onControllerColliderHitHit'), # type ControllerColliderHit is not found
  '_onDestroy': (),
  '_onDisable': (),
  '_onDrawGizmos': (),
  '_onDrawGizmosSelected': (),
  '_onEnable': (),
  '_onGUI': (),
  '_onJointBreak': (('SystemSingle', 'onJointBreakBreakForce'),),
  '_onJointBreak2D': (('UnityEngineJoint2D', 'onJointBreak2DBrokenJoint'),),
  '_onMouseDown': (),
  '_onMouseDrag': (),
  '_onMouseEnter': (),
  '_onMouseExit': (),
  '_onMouseOver': (),
  '_onMouseUp': (),
  '_onMouseUpAsButton': (),
  '_onParticleCollision': (('UnityEngineGameObject', 'onParticleCollisionOther'),),
  '_onParticleTrigger': (),
  '_onPostRender': (),
  '_onPreCull': (),
  '_onPreRender': (),
  '_onRenderImage': (('UnityEngineRenderTexture', 'onRenderImageSrc'), ('UnityEngineRenderTexture', 'onRenderImageDest'),),
  '_onRenderObject': (),
  '_onTransformChildrenChanged': (),
  '_onTransformParentChanged': (),
  '_onTriggerEnter': (('UnityEngineCollider', 'onTriggerEnterOther'),),
  '_onTriggerEnter2D': (('UnityEngineCollider2D', 'onTriggerEnter2DOther'),),
  '_onTriggerExit': (('UnityEngineCollider', 'onTriggerExitOther'),),
  '_onTriggerExit2D': (('UnityEngineCollider2D', 'onTriggerExit2DOther'),),
  '_onTriggerStay': (('UnityEngineCollider', 'onTriggerStayOther'),),
  '_onTriggerStay2D': (('UnityEngineCollider2D', 'onTriggerStay2DOther'),),
  '_onValidate': (),
  '_onWillRenderObject': (),
  '_onDrop': (),
  '_onOwnershipTransferred': (),
  '_onPickup': (),
  '_onPickupUseDown': (),
  '_onPickupUseUp': (),
  '_onPlayerJoined': (('VRCSDKBaseVRCPlayerApi', 'onPlayerJoinedPlayer'),),
  '_onPlayerLeft': (('VRCSDKBaseVRCPlayerApi', 'onPlayerLeftPlayer'),),
  '_onSpawn': (),
  '_onStationEntered': (),
  '_onStationExited': (),
  '_onVideoEnd': (),
  '_onVideoPause': (),
  '_onVideoPlay': (),
  '_onVideoStart': (),
  '_onPreSerialization': (),
  '_onDeserialization': (),
  ## Comment-outed event
  # onDataStorageAdded
  # onDataStorageChanged
  # onDataStorageRemoved
}